#include "winUI.h"

void CreateUI(HWND hwnd, int ID_BUTTON_1, int ID_INPUT_1, int ID_INPUT_2, int ID_INPUT_3)
{
    //STATIC
    CreateWindowEx(WS_EX_WINDOWEDGE,"STATIC","X",WS_VISIBLE | WS_CHILD | SS_LEFT, 5,20,15,20,hwnd, (HMENU)1,NULL, NULL);
    CreateWindowEx(WS_EX_WINDOWEDGE,"STATIC","Y",WS_VISIBLE | WS_CHILD | SS_LEFT, 5,50,15,20,hwnd, (HMENU)1,NULL, NULL);
    CreateWindowEx(WS_EX_WINDOWEDGE,"STATIC","dots",WS_VISIBLE | WS_CHILD | SS_LEFT, 145,20,60,20,hwnd, (HMENU)1,NULL, NULL);

    //BUTTONs
    CreateWindowEx(0,"BUTTON", "Send", WS_CHILD | WS_VISIBLE, 100, 100, 100, 30, hwnd,(HMENU) ID_BUTTON_1, NULL, NULL);

    //INPUTs
    CreateWindowEx(WS_EX_CLIENTEDGE,"EDIT", NULL, ES_NUMBER | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 25,10,100,30, hwnd, (HMENU) ID_INPUT_1, NULL,NULL);
    CreateWindowEx(WS_EX_CLIENTEDGE,"EDIT", NULL, ES_NUMBER | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 25,40,100,30, hwnd, (HMENU) ID_INPUT_2, NULL,NULL);
    CreateWindowEx(WS_EX_CLIENTEDGE,"EDIT", NULL, ES_NUMBER | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 190,10,30,30, hwnd, (HMENU) ID_INPUT_3, NULL,NULL);
}